"""Convert date strings to DateTime

Revision ID: e1ed456386ac
Revises: 
Create Date: 2025-04-22 15:09:42.402878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ed456386ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Профиль на сайте Wildberries', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Название продавца', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Раздел товаров', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Категория товаров', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Товаров продано', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Количество отзывов', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Рейтинг продавца', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('% выкупленных товаров', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Регистрация на Wildberries', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Юридический адрес', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Рабочие телефоны мобильные', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Рабочие телефоны городские', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Рабочие Email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Рабочие Email дополнительный источн', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Сайт', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Whatsapp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Telegram', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('VK', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Instagram', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('OK', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Среднее количество продаваемых то', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Статус компании', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Дата ликвидации', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='suppliers_pkey')
    )
    # ### end Alembic commands ###
